### ISSUE TITLE
run.sh

### ISSUE THREAD

**Issue by myke4416** [rtlsdrblog/kerberossdr#6]
Static IP address of IPADDR="0.0.0.0" in run.sh does not work properly for graph updates.  Add the following lines of code after BUFF_SIZE from previous version corrects the problem:

IPADDR=$(ip addr show wlan0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
while [ "$IPADDR" == "" ]
do
    sleep 1
    echo "waiting for network"
    IPADDR=$(ip addr show wlan0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
    echo $IPADDR
done

**Comment by ckoval7** [comment]
The run.sh file on the raspi image has something similar to this, plus some extra tid bits. I would love to see an interface name agnostic version of this so it can be seamlessly be used with wired interfaces and interface names on other platforms. For example, my Ubuntu machine uses "wlp62s0" for the WLAN.

**Comment by ckoval7** [comment]
I believe this can be marked closed with the recent merge.
