### ISSUE TITLE
Suggestion - optional text file containing all settings 

### ISSUE THREAD

**Issue by alphafox02** [rtlsdrblog/kerberossdr#8]
I haven’t looked closely at the way settings are saved and processed, but if there isn’t already one, would it be possible to have a static file containing some of the settings/options available in the web GUI which if correctly setup could override what’s selected in the GUI? I’d like to try and quickly set multiple devices up to look at the same frequency.

**Comment by ckoval7** [comment]
I'm working on adding the ability to load settings from a config file, but that would only be effective when you first load the program. Further in the future there will be software to network these devices together.

**Comment by alphafox02** [comment]
Looking forward to the networking piece, actually looking at ways to do workarounds in the meantime. As insecure and old my code is, I was going to mess around with my AWD mesh controlling software from 2008/09 (back when robin and open mesh was mostly open source) to see if I could just push updates from the cloud to each device. You’re more than welcome to see if any of that old code would be helpful to you guys. Just look at my github page.
